In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [5]:
#dataset

wine = load_wine()
X = wine.data
y = wine.target

print(X.shape)
y = to_categorical(y)

(178, 13)


In [6]:
#splitting dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

In [11]:
#model

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build ANN Model
model = Sequential()
model.add(Dense(10, activation = 'relu', input_dim = X_train.shape[1]))
model.add(Dense(3, activation = 'softmax'))
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs = 1000, verbose = 0)

In [12]:
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis = 1)
y_test_classes = np.argmax(y_test, axis = 1)

#Analysis Metrics
acc = accuracy_score(y_test_classes, y_pred_classes)
cm = confusion_matrix(y_test_classes, y_pred_classes)

print("Training Data Set")
print("Accuracy: ", acc)
print("Confusion Matrix: \n", cm)

2/2 [==============================] - 0s 5ms/step
Training Data Set
Accuracy:  0.9814814814814815
Confusion Matrix: 
 [[19  0  0]
 [ 0 20  1]
 [ 0  0 14]]
